server:
  port: 10001
spring:
  application:
    name: double-data-sourse
  datasource:
    hikari:
      db1:
        jdbc-url:  jdbc:mysql://10.0.0.36:3306/jery?serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
      db2:
        jdbc-url: jdbc:mysql://10.0.0.36:3306/rick?serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
mybatis:
  mapper-locations: classpath:mapper/**/**.xml